apiVersion: v1
kind: Secret
metadata:
  name: {{  .Values.secrets.name }}
  labels:
    {{- include "audibene-api-sqs-to-dynamodb.labels" . | nindent 4 }}  
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{  .Values.secrets.AWS_ACCESS_KEY_ID | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{  .Values.secrets.AWS_SECRET_ACCESS_KEY | b64enc }}
  AWS_DEFAULT_REGION: {{  .Values.secrets.AWS_DEFAULT_REGION | b64enc }}
  AWS_SQS_NAME: {{  .Values.secrets.AWS_SQS_NAME | b64enc }}
  FLASK_HOST: {{  .Values.secrets.FLASK_HOST | b64enc }}
  FLASK_PORT: {{  .Values.secrets.FLASK_PORT | b64enc }}
  FLASK_DEBUG: {{  .Values.secrets.FLASK_DEBUG | b64enc }}
  DYNAMODB_CREDIT_CARD_TABLE: {{  .Values.secrets.DYNAMODB_CREDIT_CARD_TABLE | b64enc }}
  DYNAMODB_PAYPAL_TABLE: {{  .Values.secrets.DYNAMODB_PAYPAL_TABLE | b64enc }}