apiVersion: v1
kind: Service
metadata:
  name: {{ include "audibene-api-sqs-to-dynamodb.fullname" . }}
  labels:
    {{- include "audibene-api-sqs-to-dynamodb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "audibene-api-sqs-to-dynamodb.selectorLabels" . | nindent 4 }}
